# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Et3rnos
email: et3rnos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Discord Bot Developer - CTF Player
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://et3rnos.github.io" # the base hostname & protocol for your site
flag: "DS{4_1337_f14g_f0r_y0ur_us3}"

# Build settings
markdown: kramdown
